# Generated by Django 5.1.6 on 2025-02-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0002_journalentry_familymember_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='notes',
        ),
    ]
