# Generated by Django 4.2.1 on 2025-06-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0004_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='happ.doctor'),
        ),
    ]
