# Generated by Django 5.0.3 on 2025-06-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0005_userprofile_assigned_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_id',
            new_name='doctor_doctor_id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='email',
            new_name='doctor_email',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='full_name',
            new_name='doctor_full_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='phone',
            new_name='doctor_phone',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='doctor_speciality',
        ),
    ]
