# Generated by Django 5.0.3 on 2025-06-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0006_rename_doctor_id_doctor_doctor_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
