# Generated by Django 5.0.3 on 2025-06-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0007_doctor_unique_id_userprofile_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='doctor_user',
        ),
    ]
