# Generated by Django 5.0.3 on 2025-06-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0008_rename_user_doctor_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
