# Generated by Django 5.0.3 on 2025-06-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0009_alter_userprofile_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
